#!/system/bin/sh
# Vacuum and reindex sqlite databases on boot

LOGCAT="log -p i -t sqlite3"
LOG=/system/etc/logs/11sqlite3.log

function sqlite3() {
	# Mount system
    	$LOGCAT "Mounting /system";
    	busybox mount -o remount,rw /system;

	# Check if log dir exists
	if [ ! -d /system/etc/logs ]; then
		$LOGCAT "/system/etc/logs not found! Creating dir...";
		mkdir -p /system/etc/logs;
	fi
	
    	# Create log file
    	$LOGCAT "Creating new LOG file";
    	busybox date > $LOG;
	
	# Check if logfile was created properly
	if [ ! -e $LOG ]; then
    	    $LOGCAT "Error: Unable to create logfile!"
    	    exit 1;
    	fi
	
	$LOGCAT "Beginning 1 minute delay..."
	sleep 60;
	$LOGCAT "Executing SQlite3!"
	
	busybox echo "Beginning /data optimization" | tee -a $LOG
	x=0;
	for i in \
	`busybox find /data -iname "*.db"`;
	do \
		/system/xbin/sqlite3 $i 'VACUUM;' | tee -a $LOG;
		/system/xbin/sqlite3 $i 'REINDEX;' | tee -a $LOG;
		x=$((x+1));
	done;
	$LOGCAT "Optimized $x /data databases";
	busybox echo "Optimized $x /data databases" | tee -a $LOG
	busybox echo " " | tee -a $LOG
	
	busybox echo "Beginning /sdcard optimization" | tee -a $LOG
	x=0;
	for i in \
	`busybox find /sdcard -iname "*.db"`;
	do \
		/system/xbin/sqlite3 $i 'VACUUM;' | tee -a $LOG;
		/system/xbin/sqlite3 $i 'REINDEX;' | tee -a $LOG;
		x=$((x+1));
	done;
	$LOGCAT "Optimized $x /sdcard databases";
	busybox echo "Optimized $x /sdcard databases" | tee -a $LOG

	$LOGCAT "/system/etc/11sqlite3 complete!";
	busybox echo "SQlite3 optimization complete!" | tee -a $LOG
}

$LOGCAT "Running /system/etc/11sqlite3...";
sqlite3 &
